---
# Create and configure Emperor mode of uWSGI
# For details see: https://uwsgi-docs.readthedocs.org/en/latest/Emperor.html

- name: Configure uWSGI emperor
  template: src=emperor/{{ item.src }} dest=/etc/uwsgi/{{ item.dest }} backup=yes owner=root group=root
  with_items:
    - { src: 'emperor.ini.jinja2', dest: 'emperor.ini' }
    - { src: 'vassals-default.ini.jinja2', dest: 'vassals-default.ini' }

- name: Configure Emperor via System V
  copy: src=emperor/system-v dest=/etc/init.d/uwsgi owner=root group=root mode=755
  when: uwsgi_initd

- name: Setup Emperor via System V
  shell: update-rc.d uwsgi defaults
  when: uwsgi_initd

- name: Configure Emperor via Upstart
  copy: src=emperor/upstart.conf dest=/etc/init/uwsgi.conf owner=root group=root mode=0644
  when: not uwsgi_initd

- name: Run Emperor daemon
  service: name=uwsgi state=started enabled=yes
